### ISSUE TITLE
Docker deployment fails to run: No module named 'ecg_qc'

### ISSUE THREAD

**Issue by borisbaldassari** [Aura-healthcare/seizure_detection_pipeline#2]
I have followed the steps described in the repo's readme to setup the Aura docker images. 

After issuing the docker-compose up command, images are being built and after some time setup is ready. But when I try to access:
* port 80 it redirects to https, no connection.
* port 8082 I get a 403 forbidden
* port 5000 (mlflow) the list of experiments/models is empty.
* port 8080 (airflow) I get a "DAG import error" saying "ModuleNotFoundError: No module named 'ecg_qc'"

Full error report in the 8080 UI is 
````
Broken DAG: [/opt/airflow/dags/seizure_detection_pipeline.py] Traceback (most recent call last):
  File "/opt/airflow/dags/seizure_detection_pipeline.py", line 7, in <module>
    from src.usecase.apply_ecg_qc import apply_ecg_qc
  File "/opt/airflow/src/usecase/apply_ecg_qc.py", line 5, in <module>
    import ecg_qc
ModuleNotFoundError: No module named 'ecg_qc'
````

Docker log is attached below:
[aura_setup.log](https://github.com/Aura-healthcare/seizure_detection_pipeline/files/7167758/aura_setup.log)

**Comment by ncleyetmarrel** [comment]
Thanks for raising these issues.
This project is currently under developement, that is why some errors may occur.I'm sharing with you some explanations:
- port 80 is not supposed to be accessed, no service is set up on this port
- port 8082 : 403 forbidden appears because the folder containing the generated great expectation doc is empty. If you run some data validation and generate some doc, you will just need to refresh the page. Unfortunately the data validation task is not implemented yet.
- port 5000 : the ML experiment tasks are not implemented yet, hence the list is empty
- port 8080 : the last available version of ecg_qc is not up to date, currently we are manually installing ecg_qc inside the airflow container, via a git clone, after setting up all containers. An up to date version will be released on PyPI soon to avoid this step.

For now, the first task (`read_ecg_channel.py`) is specific to a private database, provided by a medical center. We are working on this to make this task more generic and support open databases.
For the moment, only the tasks before `remove_noisy_segments.py` (included) are implemented. Once open databases will be supported, you'll be able to run those individually, as shown in the readme.

**Comment by borisbaldassari** [comment]
Hi @ncleyetmarrel 
Thanks a lot for the update! I'll wait until you're done then.
